include settings
SHELL = /bin/bash
lang = $(shell basename $(PWD))

T2TFILES = changes.t2t userGuide.t2t keyCommands.t2t
HTMLFILES = $(patsubst %.t2t,%.html,$(T2TFILES))

convert: | utf $(HTMLFILES) ug-stats.txt ug-stats-diff.txt commit

%.html: %.t2t
	# convert $< to $@
	@txt2tags -q -o $@ $<

keyCommands.t2t: userGuide.t2t
	# creating keyCommands.t2t from userGuide.t2t
	@python2.7 ../scripts/keyCommandsDoc.py

ug-stats.txt: userGuide.t2t
	# recalculating userGuide stats
	@python ../scripts/stats.py


ug-stats-diff.txt: ug-stats.txt
	# rebuilding userGuide stats differences
	@../scripts/remakeStats.sh $(lang)

utf: changes.t2t userGuide.t2t 
	# checking for non utf8 or ascii files $?
	@../scripts/checkEncoding.sh

commit: $(HTMLFILES) ug-stats.txt ug-stats-diff.txt
	# committing changes $?
	@mfiles=`git status -s -uno . | grep -i '.[html|txt]$$' | awk '{printf(" %s", $$2)}'`; \
	if [ "$$mfiles" != "" ]; then \
	echo "${lang}: updated $$mfiles" | \
	git commit -q -F - $$mfiles; \
	fi

# .PHONY : convert
