#!/usr/bin/env python
import cgi
from re import findall
from subprocess import PIPE, Popen
from addresses import addresses

form = cgi.FieldStorage() # instantiate only once!

print "Content-type: text/plain\n"


author = form['author'].value if form.has_key('author') else 'pratchett'
action = form['action'].value if form.has_key('action') else 'wrote'
body = form['body'].value if form.has_key('body') else 'the colour of magic'
title = form['title'].value if form.has_key('title') else 'disc world'
subject = "SRT %s" % title
body = "%s %s %s\n\n%s" %(author, action, title, body)


rcpts = []
for key in addresses.keys():
    if findall(key+'/', body):
        rcpts.extend(addresses[key])
rcpts.extend(addresses['all'])

p1 = Popen(['echo', '-e', body], stdout=PIPE)
p2 = Popen(['mail', '-s', subject, ", ".join(rcpts)], stdin=p1.stdout)

f = open('/tmp/mail/webhook.log', 'a')
f.write("--- start ---\n")
f.write("rcpts: %s\n" % ", ".join(rcpts))
f.write("subject: %s\n" % subject)
f.write("body: %s\n" % body)
f.write("-- raw data ---\n")
for key in form.keys():
    f.write("%s='%s'\n" % (key, form[key].value))
f.write("--- end ---\n")
f.close()
print "Notification sent."
