#!/usr/bin/env python
import os
import cgi
import re
from subprocess import PIPE, call
from addresses import addresses, email
import poChecker

SRT_PATH = "/home/nvdal10n/mr/srt"

form = cgi.FieldStorage() # instantiate only once!

print "Content-type: text/plain\n"


author = form['author'].value if form.has_key('author') else 'pratchett'
action = form['action'].value if form.has_key('action') else 'wrote'
body = form['body'].value if form.has_key('body') else 'the colour of magic'
title = form['title'].value if form.has_key('title') else 'disc world'
subject = "SRT %s" % title
body = "%s %s %s\n\n%s" %(author, action, title, body)


rcpts = []
for key in addresses.keys():
    if re.search('/test/', body):
        break
    if re.search('(\s+/%s/)|(\.%s\.po)' %(key, key), body):
        rcpts.extend(addresses[key]['email'])

# Check any po files in this commit.
call([os.path.join(SRT_PATH, "scripts", "svn"), "update", "-q"], cwd=SRT_PATH)
poFiles = re.findall(r'(?<=\s)/.*\.po', body)
for po in poFiles:
    po = os.path.join(SRT_PATH, po[1:])
    c = poChecker.PoChecker(po)
    if not c.check():
        body += "\n\n\n" + c.getReport().encode("UTF-8")

email(rcpts, subject, body)

f = open('/tmp/webhook.log', 'a')
f.write("--- start ---\n")
f.write("rcpts: %s\n" % ", ".join(rcpts))
f.write("subject: %s\n" % subject)
f.write("body: %s\n" % body)
f.write("-- raw data ---\n")
for key in form.keys():
    f.write("%s='%s'\n" % (key, form[key].value))
f.write("--- end ---\n")
f.close()
print "Notification sent."


if re.search("/website/", body):
    print "running website post-commit hook."
    pc = '/home/nvdal10n/ikiwiki/publish/post-commit'
    call([pc])
    print "finnished website post-commit hook."

if re.search(r"\s+/([^/\s]+/)+\w+\.t2t\b", body):
    print "running t2t conversion"
    call(["./convertT2t.sh"], cwd="/home/nvdal10n/mr/srt_conv/scripts")
    print "finished running t2t conversion"
